### ISSUE TITLE
cpp version of closest number to zero 

### ISSUE THREAD

**Issue by mrsparkle-70** [durgesh2001/hacktoberfest_demo#22]
There should be a cpp version for closest number to zero problem solution

**Comment by mrsparkle-70** [comment]
i want to get assigned to this issue @durgesh2001

**Comment by durgesh2001** [comment]
assigned,contribute by your awesome code.

**Comment by DhirajGilda** [comment]
@mrsparkle-70 is this issue still open

**Comment by deepak8321** [comment]
i can done

**Comment by sayanm16** [comment]
Hey @durgesh2001 can u pls assign me with this issue pls
